{{- if .Values.routerSpec.enableRouter -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ .Release.Name }}-router-service"
  labels:
  {{- include "chart.routerLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: "router-sport"
      port: {{ .Values.routerSpec.servicePort }}
      targetPort: {{ .Values.routerSpec.containerPort }}
      protocol: TCP
  selector:
  {{- include "chart.routerLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: benchmark-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: benchmark-svc
  selector:
  {{- include "chart.routerLabels" . | nindent 4 }}
---
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: router-metrics-monitor-{{ .Values.routerSpec.routingLogic }}
  namespace: monitoring
  labels:
    environment: {{ .Values.routerSpec.labels.environment }}
    release: kube-prom-stack
spec:
  endpoints:
    - path: /metrics
      port: router-sport
  namespaceSelector:
      matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      environment: {{ .Values.routerSpec.labels.environment }}
      release: {{ .Values.routerSpec.labels.release }}


{{- end }}

