servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "deepseek"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
    replicaCount: 1

    requestCPU: 10
    requestMemory: "22.8Gi"
    requestGPU: 1

    pvcStorage: "50Gi"
    pvcAccessMode:
      - ReadWriteOnce

    vllmConfig:
      enableChunkedPrefill: false
      enablePrefixCaching: false
      maxModelLen: 32768
      dtype: "bfloat16"
      extraArgs: ["--disable-log-requests", "--gpu-memory-utilization", "0.95"]

    hf_token: "UNSET"
